version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - "${PORT}:5000"
    depends_on:
      - mongo
      - mysql
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    ports:
      - "3307:3306"
    volumes:
      - .config:/docker-entrypoint-initdb.d
      

