version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - "${PORT}:${PORT}"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

